<a href="https://colab.research.google.com/github/BasShogun/demo-DM-22/blob/main/SebastianDuenas_BachChoraleProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BACHE CHORALE PROJECT

In [11]:
import keras
keras.__version__

'2.9.0'

In [12]:
##Download the dataset
!wget https://raw.githubusercontent.com/zacharski/ml-class/master/data/bach.zip
##unzip data
!unzip bach.zip

--2022-12-09 13:26:10--  https://raw.githubusercontent.com/zacharski/ml-class/master/data/bach.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41761 (41K) [application/zip]
Saving to: ‘bach.zip’

bach.zip            100%[===================>]  40.78K  --.-KB/s    in 0.01s

2022-12-09 13:26:10 (3.88 MB/s) - ‘bach.zip’ saved [41761/41761]

Archive:  bach.zip
  inflating: bach.csv

In [13]:
##import pandas and load the bach csv file
import pandas as pd
chord = pd.read_csv('bach.csv')
##Set index
chord = chord.set_index('event_number')
chord

,choral_ID,C,C#,D,D#,E,F,F#,G,G#,A,A#,B,bass,meter,chord_label
event_number,,,,,,,,,,,,,,,,
1,000106b_,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
2,000106b_,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,5,C_M
3,000106b_,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,2,C_M
4,000106b_,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
5,000106b_,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,2,F_M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,015505b_,NO,NO,YES,NO,NO,NO,NO,YES,NO,NO,YES,NO,G,4,G_m
106,015505b_,NO,NO,YES,NO,NO,NO,NO,YES,NO,YES,NO,NO,G,3,G_m
107,015505b_,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,C,5,C_M
108,015505b_,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,YES,NO,C,3,C_M
109,015505b_,NO,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,4,F_M

In [14]:
from IPython.lib.display import join
music_lbl = chord['chord_label']
music_ftr = chord.drop(['chord_label','choral_ID'], axis=1)
music_collec = pd.get_dummies(music_ftr)
music_collec

,meter,C_NO,C_YES,C#_NO,C#_YES,D_NO,D_YES,D#_NO,D#_YES,E_NO,...,bass_C#,bass_D,bass_D#,bass_Db,bass_E,bass_Eb,bass_F,bass_F#,bass_G,bass_G#
event_number,,,,,,,,,,,,,,,,,,,,,
1,3,0,1,1,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
2,5,0,1,1,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
3,2,0,1,1,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,3,0,1,1,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
5,2,0,1,1,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,4,1,0,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,1,0
106,3,1,0,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,1,0
107,5,0,1,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
108,3,0,1,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
109,4,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0

##Dividing data into train and test

KNN ALGORITHM

In [16]:
from sklearn.model_selection import train_test_split
music_train_ftr, music_test_ftr, music_train_lbl, music_test_lbl = train_test_split(music_collec, music_lbl, test_size= 0.2, random_state=25)
from sklearn.neighbors import KNeighborsClassifier #importing KNN classifier module
knn = KNeighborsClassifier(n_neighbors=3)
print(knn.get_params())
knn.fit(music_train_ftr, music_train_lbl)
predictions = knn.predict(music_test_ftr)
from sklearn.metrics import accuracy_score
print("accuracy of knn algorithm is "), accuracy_score(music_test_lbl, predictions)

{'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 3, 'p': 2, 'weights': 'uniform'}
accuracy of knn algorithm is

(None, 0.7105030891438658)

GRID SEARCH ALGORITHM

In [20]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV

hyperparam_grid = [{'max_depth': [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], 'min_samples_split': [2, 3, 4, 5, 6]}]

clf = tree.DecisionTreeClassifier(criterion='entropy')
grid_search = GridSearchCV(clf, hyperparam_grid,cv=50)
grid_search.fit(music_train_ftr, music_train_lbl)
grid_search.best_params_
predictions= grid_search.best_estimator_.predict(music_test_ftr)
print("accuracy of decision tree is: ", accuracy_score(music_test_lbl, predictions))

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=50.
  warnings.warn(

accuracy of decision tree is:  0.733451015004413

BAGGING AND PASTING ALGORITHM

In [23]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='entropy')
bagging_clf = BaggingClassifier(clf, n_estimators=50, max_samples=.5, bootstrap=True, n_jobs=1)
pasting_clf = BaggingClassifier(clf, n_estimators=40, max_samples=.1, bootstrap=False, n_jobs=1)
bagging_clf.fit(music_train_ftr, music_train_lbl)
pasting_clf.fit(music_train_ftr, music_train_lbl)
predictions = bagging_clf.predict(music_test_ftr)
print("accuracy of bagging algorithm is: ",accuracy_score(music_test_lbl, predictions))
predictions = pasting_clf.predict(music_test_ftr)
print("accuracy of pasting algorithm is: ",accuracy_score(music_test_lbl, predictions))

accuracy of bagging algorithm is:  0.736981465136805
accuracy of pasting algorithm is:  0.7263901147396293